services:
    # PHP Service
    php-fpm:
        build:
            context: ./php-fpm
            args:
                username: ${USER_NAME}
                useruid: ${USER_UID}
        container_name: php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports:
            - "9000:9000"
        networks:
            default:
                ipv4_address: 80.10.1.105

    # Nginx Service
    webserver:
        image: nginx:1.26.0
        container_name: web-server
        restart: unless-stopped
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        volumes:
            - ../:/var/www
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 80.10.1.104

    # MySQL Service
    mysql:
        build:
            context: ./mysql-dockerfile
            args:
                MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
                MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
                MYSQL_USER: ${MYSQL_DB_USERNAME}
                MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
        container_name: mysql-db
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            default:
                ipv4_address: 80.10.1.101

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 80.10.1.0/24
